public with sharing class Constants {
    // Property Approval Statuses
    public static final String PROPERTY_STATUS_DRAFT = 'Draft';
    public static final String PROPERTY_STATUS_SUBMITTED = 'Submitted';
    public static final String PROPERTY_STATUS_APPROVED = 'Approved';
    public static final String PROPERTY_STATUS_REJECTED = 'Rejected';
    
    // Property Status
    public static final String PROPERTY_AVAILABLE = 'Available';
}